baseURL = "https://bus32.llc"
languageCode = "en-us"
title = "BUS32 Consulting LLC"
themesDir = "themes"
theme = "hugo-hero-theme"
publishDir = "docs"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.png"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "BUS32 Consulting Services LLC"
    meta_og_title = "BUS32 Consulting LLC"
    meta_og_type = "website"
    meta_og_url = "https://bus32.llc"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "BUS32 Consulting LLC"
    meta_twitter_card = "summary"
    meta_twitter_site = "@bus32llc"
    meta_twitter_creator = "@bus32llc"

#[[menu.main]]
#	name = "Services"
#	url = "/services/"
#    weight = 1

#[[menu.main]]
#    name = "Work"
#    url = "/work/"
#    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

#[[menu.main]]
#    name = "History"
#    url = "/history/"
#    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
